name: expenses
recipe: laravel

config:
  php: '8.1'
  webroot: src/public
  excludes:
    - src/node_modules
    - src/vendor

services:
  appserver:
    type: 'php:8.1'
    webroot: ./src/public
    xdebug: true
    run:
      - cd $LANDO_MOUNT/src && composer install && php artisan migrate -v --no-interaction && php artisan vendor:publish --all -v --no-interaction && php artisan cache:clear -v --no-interaction
  mail:
    type: mailhog:v1.0.0
    portforward: false
    hogfrom: []
  node:
    type: node:16
    ssl: false
    user: node
    run:
      - cd $LANDO_MOUNT/src && npm install
    command: npm run watch > /tmp/node.log 2>&1

tooling:
  npm:
    service: node
    description: Runs npm.
    user: node
    cmd: npm

  npm-logs:
    service: node
    description: Follow the log from the node container to check for errors during vue compiling process.
    user: node
    cmd: tail --follow /tmp/node.log

  npx:
    service: node
    description: Runs npx
    cmd: npx

  artisan:
    service: appserver
    description: Runs Laravel's CLI Artisan
    dir: /app/src
    cmd: php artisan

  npm-install:
    service: node
    description: Install node dependencies using npm inside node container.
    user: node
    cmd: nopm install
